name: Update README and Create Spring Boot Project Structure

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install SDKMAN and Spring CLI
        env:
          HOME: /home/runner
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install springboot

      - name: Backup README
        run: |
          mv README.md README.md.bak

      - name: Create Spring Boot Project Structure
        env:
          HOME: /home/runner
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          spring init --dependencies=web,data-jpa,h2 --build=maven --java-version=17 --name=dynamic-assessment-generation --package-name=com.example.dynamicassessmentgeneration --force --extract
          ls -la /home/runner/work/dynamic-assessment-generation/dynamic-assessment-generation
          ls -la /home/runner/work/dynamic-assessment-generation

      - name: Debug Working Directory Before Move
        run: |
          echo "Current working directory before move: $(pwd)"
          ls -la

      - name: Restore README
        run: |
          mv README.md.bak README.md

      - name: Move Project Files
        run: |
          rsync -av --ignore-existing /home/runner/work/dynamic-assessment-generation/dynamic-assessment-generation/ ${{ github.workspace }}
          rm -rf /home/runner/work/dynamic-assessment-generation/dynamic-assessment-generation

      - name: Debug Working Directory After Move
        working-directory: ${{ github.workspace }}
        run: |
          echo "Current working directory after move: $(pwd)"
          ls -la

      - name: Change to Root Directory
        working-directory: ${{ github.workspace }}
        run: |
          echo "Changing to root directory"
          cd ${{ github.workspace }}
          echo "Changed to root directory: $(pwd)"
          ls -la

      - name: Debug Working Directory
        working-directory: ${{ github.workspace }}
        run: |
          echo "Current working directory: $(pwd)"
          ls -la

      - name: Update README
        working-directory: ${{ github.workspace }}
        run: |
          # Append the current date and time to the README file
          echo "Last updated: $(date '+%Y-%m-%d %H:%M:%S')" >> README.md

      - name: Commit and push changes
        working-directory: ${{ github.workspace }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .