name: Update README and Create Spring Boot Project Structure

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Backup README
        run: |
          mv README.md README.md.bak

      - name: Create Spring Boot Project Structure
        run: |
          mvn archetype:generate -DgroupId=com.example -DartifactId=dynamic-assessment-generation -DarchetypeGroupId=org.springframework.boot -DarchetypeArtifactId=spring-boot-archetype -DarchetypeVersion=2.5.4 -DinteractiveMode=false
          ls -la $GITHUB_WORKSPACE

      - name: Restore README
        run: |
          mv README.md.bak README.md

      - name: Debug Directory Structure
        run: |
          echo "Directory structure:"
          ls -la $GITHUB_WORKSPACE

      - name: Update README
        run: |
          # Append the current date and time to the README file
          echo "Last updated: $(date '+%Y-%m-%d %H:%M:%S')" >> README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update README and create Spring Boot project structure"
          git push